name:                servant-cli
version:             0.1.0.1
github:              "mstksg/servant-cli"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"
tested-with:         GHC >= 8.6

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Command line interface for Servant API clients
category:            Web

description: |
  Parse command line arguments into a servant client, from a servant API,
  using /optparse-applicative/ for parsing, displaying help, and
  auto-completion.

  Hooks into the annotation system used by /servant-docs/ to provide descriptions
  for parameters and captures.

  See @example/greet.hs@ for an example usage, and the
  <https://hackage.haskell.org/package/servant-cli README> for a tutorial.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.12 && < 5
- bytestring
- vinyl
- text
- optparse-applicative
- containers
- servant >= 0.15


library:
  source-dirs: src
  dependencies:
  - case-insensitive
  - filepath
  - free
  - http-types
  - profunctors
  - recursion-schemes
  - servant-client-core >= 0.15
  - servant-docs
  - functor-combinators
  - transformers

executables:
  greet-cli:
    main:                greet.hs
    source-dirs:         example
    dependencies:
    - aeson
    - http-client
    - random
    - servant-cli
    - servant-client
    - servant-server
    - warp
